# Image base
FROM nginx:alpine

# Borra el contenido por defecto de nginx
# RUN rm -rf /usr/share/nginx/html/*

# Copia los archivos de la aplicación al contenedor
# COPY src /usr/share/nginx/html

# Expone el puerto 80
EXPOSE 80

# Comando por defecto para ejecutar nginx en primer plano
# CMD ["nginx", "-g", "daemon off;"]